// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwczPv7isAmncwr5XJNraTUX1CyM3YERQ',
    appId: '1:881023077695:web:2ee8b02fb07e33ee7e978a',
    messagingSenderId: '881023077695',
    projectId: 'test-f19d2',
    authDomain: 'test-f19d2.firebaseapp.com',
    storageBucket: 'test-f19d2.firebasestorage.app',
    measurementId: 'G-BCG8P1MP8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFF03k3iHvPcLOCKfobf9Oc47GC2dSorM',
    appId: '1:881023077695:android:52181096f63985b57e978a',
    messagingSenderId: '881023077695',
    projectId: 'test-f19d2',
    storageBucket: 'test-f19d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP7hg3rsmDXr5WxSdkEALLc582FKvkxjU',
    appId: '1:881023077695:ios:e1508fe1943c51d27e978a',
    messagingSenderId: '881023077695',
    projectId: 'test-f19d2',
    storageBucket: 'test-f19d2.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP7hg3rsmDXr5WxSdkEALLc582FKvkxjU',
    appId: '1:881023077695:ios:e1508fe1943c51d27e978a',
    messagingSenderId: '881023077695',
    projectId: 'test-f19d2',
    storageBucket: 'test-f19d2.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwczPv7isAmncwr5XJNraTUX1CyM3YERQ',
    appId: '1:881023077695:web:065fc64439d7abde7e978a',
    messagingSenderId: '881023077695',
    projectId: 'test-f19d2',
    authDomain: 'test-f19d2.firebaseapp.com',
    storageBucket: 'test-f19d2.firebasestorage.app',
    measurementId: 'G-SX0CMV5LHE',
  );
}
